server:
  port: 9090

spring:
  application:
    name: fdsevaldemo

  kafka:
    bootstrap-servers: localhost:9092

    streams:
      auto-startup: false
      transaction:
        application-id: fds-transaction-streams
        properties:
          bootstrap.servers: localhost:9092
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          state.dir: /tmp/kafka-streams/transaction
      aggregate:
        application-id: fds-aggregate-streams
        properties:
          bootstrap.servers: localhost:9092
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          state.dir: /tmp/kafka-streams/aggregate
      statics:
        application-id: fds-statics-streams
        properties:
          bootstrap.servers: localhost:9092
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          state.dir: /tmp/kafka-streams/statics

fds:
  window-size-seconds: 60

app:
  kafka:
    topics:
      transactions: transactions
      aggregateAlerts: fds-alerts-aggregate
      staticsAlerts: fds-alerts-statics
