{
  "type": "record",
  "name": "TransactionEvent",
  "namespace": "kr.co.kimga.fdsevaldemo.model",
  "fields": [
    {
      "name": "transactionId",
      "type": "string"
    },
    {
      "name": "accountId",
      "type": "string"
    },
    {
      "name": "type",
      "type": "kr.co.kimga.fdsevaldemo.model.TransactionEventType",
      "symbols": ["BUY", "SELL"]
    },
    {
      "name": "quantity",
      "type": "long"
    },
    {
      "name": "price",
      "type": "long"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
